version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
      - "9200:9200"
    networks:
      - monitoring
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - "5601:5601"
    networks:
      - monitoring
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL="http://elasticsearch:9200"

  metric-setup:
    image: docker.elastic.co/beats/metricbeat:7.0.0
    networks:
      - monitoring
    depends_on: 
      - elasticsearch
      - kibana
    command: setup -E setup.kibana.host=kibana:5601 -E output.elasticsearch.hosts=["elasticsearch:9200"]

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.0.0
    networks:
      - monitoring
    depends_on:
      - elasticsearch
      - kibana
      - metric-setup
    user: root
    volumes:
      - "./metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/proc:/hostfs/proc:ro"
    command: metricbeat -e -E output.elasticsearch.hosts=["elasticsearch:9200"]

volumes:
  es_data:

networks:
  monitoring:
